version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Get browser data
          command: npm run getdata

      - run:
          name: Build
          command: npm run build

      - run:
          name: Deploy on Vercel
          command: npm run build

      - run:
          name: Tweet
          command: npm run tweet

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  weekly-workflow:
    triggers:
      - schedule:
          cron: '0 14 * * 1'
          filters:
            branches:
              only:
                - master
    jobs:
      - build
